name: core_icon
version: 0.0.8
author: Brandon White <jennexproject@gmail.com>
description: A set of core icon custom elements. Based on the Google Polymer project CoreIcon of a similar name (https://www.polymer-project.org/0.5/docs/elements/icons.html).
homepage: https://google.com/+BrandonWhite
environment:
  sdk: '>=1.8.5 <2.0.0'
