name: core_elements
version: 0.0.6
author: Brandon White
description: A set of core custom elements. Based on the Google Polymer project of a similar name (https://www.polymer-project.org/0.5/docs/elements/).
homepage: http://jennex.it/now/dev/
